### ISSUE TITLE
Is binary supported?

### ISSUE THREAD

**Issue by naartjie** [seegno/primus-objc#10]
Does seegno/primus-emitter-objc#1 mean that binary is not supported? 

Can you send binary data? or emit an event with binary data? How would one do it?

**Comment by nunofgs** [comment]
You are correct, binary frames are no longer directly supported using the JSON parser, which I actually believe to be more in line with the Javascript [Primus](https://github.com/primus/primus) library.

To send binary data we'd need a *binary* parser (as described in Primus [here](https://github.com/primus/primus#getting-started)). This is easily implemented by following the JSON parser example.

@naartjie I honestly haven't needed to send binary data yet. Do you have a need for this feature at the moment?

**Comment by naartjie** [comment]
> I honestly haven't needed to send binary data yet. Do you have a need for this feature at the moment?

@nunofgs My use case is I want to push a profile image to a user, but I suppose as a workaround, I could send him an `image-ready` event, to tell him to pull it from a URL once it's on the server. It's just more steps involved, but it will work fine.

Thanks for the info!!
