### ISSUE TITLE
How to target iOS?

### ISSUE THREAD

**Issue by katopz** [seegno/primus-objc#14]
Far as I know I just can't switch target to iOS and it just working.
So the question is anyone happen to have iOS target example?

Any hint is welcome. Thanks!

**Comment by nunofgs** [comment]
Hi katopz,

The tests are only running in OS X at the moment but you can use this library in an iOS project with no issues.

Are you using Cocoapods? It should work just fine for iOS projects by simply requiring 'Primus' as a dependency.

**Comment by katopz** [comment]
Hi @nunofgs 

Oh sorry, It's my bad (lazy) habit to see all things working via the tests And begin from that point.
But no worry! I'm feeling brave enough to start from scratch and it connected now. Thanks!

Cheers.
