### ISSUE TITLE
No transformer specified.

### ISSUE THREAD

**Issue by black-lotus** [seegno/primus-objc#18]
First of all, thank you for making this awesome library.
I copy your sample code from objc and i was translate it to swift like this

```
let url: NSURL = NSURL(string: "http://localhost:8080/primus")!
let options: PrimusConnectOptions = PrimusConnectOptions()
let primus: Primus = Primus(URL: url, options: options)
```

When app is running, it's getting error like this 
I have no idea what it is and how to resolve it

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'No transformer specified.'`

Any help would be appreciated.

Thank you

**Comment by nunofgs** [comment]
Hi @black-lotus, thank you for the kind words.

This library attempts to be "smart" and autodetect the transformer by choosing from a predefined [list](https://github.com/seegno/primus-objc/blob/master/Primus/Core/PrimusTransformers.m#L27).

You likely only need to import the transformer library as described in the readme [here](https://github.com/seegno/primus-objc#installation).

You can also disable the _autodetect_ mechanism if it is choosing the wrong framework in your case. To do that, just pass 'autodetect = NO' in your PrimusConnectOptions object, and then [manually](https://github.com/seegno/primus-objc#getting-started) pass the transformer class.

**Comment by black-lotus** [comment]
Hi,

Thanks for help, i have already test all of your solutions, but none of them was successfuly.
There's error with xcode compiler.
I will post more detail as soon as possible (i'm on my way to go home after vacation)

Thank you in advance

**Comment by black-lotus** [comment]
Hi @nunofgs, i got this message when set `PrimusConnectOptions().transformerClass ` as SocketRocketClient 

this is my code

```
let options: PrimusConnectOptions = PrimusConnectOptions()
options.transformerClass = SocketRocketClient().classForCoder
let primus: Primus = Primus(URL: url, options: options)
```

this is the error message that i got 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SocketRocketClient", referenced from:
      type metadata accessor for __ObjC.SocketRocketClient in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thank you in advance

**Comment by nunofgs** [comment]
Looks like you might be passing the class incorrectly. The equivalent in Swift to Objective C's `-class` seems to be: `dynamicType`.

Can you try:

`options.transformerClass = SocketRocketClient.dynamicType`

If it doesn't work, try also:

`options.transformerClass = object_getClass(SocketRocketClient)`

**Comment by black-lotus** [comment]
Hi @nunofgs still error :(

![untitled](https://cloud.githubusercontent.com/assets/3261560/18939520/0dcc3c96-862b-11e6-80ca-80db686815a4.gif)

this `SocketRocketClient.dynamicType` does not work, since it's return `Type` not `AnyClass`
this `object_getClass(SocketRocketClient)` same error like before

**Comment by nunofgs** [comment]
@black-lotus I was able to get this to work in Swift with this:

```swift
let url:NSURL = NSURL(string: "http://localhost:9090/primus")!
let options:PrimusConnectOptions = PrimusConnectOptions()
        
options.transformerClass = SocketRocketClient.self
options.autodetect = false

...
```

Don't forget to add the following to your "XXX-Bridging-Header.h" file:

```objective-c
#import <Primus/Primus.h>
#import <Primus/SocketRocketClient.h>
```

**Comment by black-lotus** [comment]
@nunofgs I'm still getting error after following your sulutions

![untitled](https://cloud.githubusercontent.com/assets/3261560/19062001/f4e65254-8a1f-11e6-8f4d-b281fa1e15c1.gif)

can u give us your samples :)

Thanks a lot by the way

**Comment by nunofgs** [comment]
Here's a small sample:

[PrimusSwiftTest.zip](https://github.com/seegno/primus-objc/files/512605/PrimusSwiftTest.zip)

By the way, do you have the SocketRocket pod installed?

**Comment by black-lotus** [comment]
I am using pod, and "SocketRocket" & "Primus" already installed
I thought because i was using xcode 8, but when i run your sample it's work like a charm
your project doesn't give an erroy anyway 👍 
but why the socket is not open yet :(

My local server is runing and works if i use primus client to connect with.
this is the screen that i have captured

![untitled](https://cloud.githubusercontent.com/assets/3261560/19188572/c181392a-8cbc-11e6-8eac-b0e370d62d68.gif)

**Comment by nunofgs** [comment]
@black-lotus I can get it to connect and print "open" successfully.

Change the implementation to:

```swift
typealias Block = @convention(block) () -> ()

let primus: Primus = Primus(url: url as URL!, options: options)
let cb: Block = {
    print("open")
}

primus.on("open", listener: unsafeBitCast(cb, to: AnyObject.self))
```

The reason this is needed is because you need to pass an objective-c block to the event listener (and not a Swift closure).

For primus server-side I used the "echo" example [available here](https://github.com/primus/primus/tree/master/examples/echo).

**Comment by nunofgs** [comment]
Closing for now since the library itself has no issues. Feel free to keep commenting and I'll help as much as I can.

**Comment by black-lotus** [comment]
I did little changes in url format and it's working
here my code for someone who face with the same issue

```
let uuid: String = UIDevice.currentDevice().identifierForVendor!.UUIDString.lowercaseString
let arc: Int = Int(arc4random_uniform(99999))
        
let components = NSURLComponents()
components.scheme = "http"
components.host = "localhost"
components.path = "/primus/\(arc)/\(uuid)/websocket"
components.port = 8080

// get url
let url = components.URL!
```
